name: Build Series Database

on:
  workflow_dispatch:
  push:
    paths:
      - 'series/**'
      - 'scripts/build-seriesbase.py'
      - '.github/workflows/update-database.yml'

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Python installieren
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Datenbank erzeugen
        run: python scripts/build-seriesbase.py

      - name: Änderungen committen
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add "series.json"

          git diff --cached --quiet || git commit -m "Series-Base aktualisiert"

          git push